spring.application.name=StyleFit

spring.datasource.url=jdbc:h2:mem:stylefit;MODE=MySQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

jwt.secret=8TUI9nFnZWLRSm+vEWSCVeSYVY42WqGZx2m4lEcxKE7Zun2qvzJ8HXS5gDnsbntEiFfaG89V7jz2czEuIoTuFA==
jwt.issuer=StyleFit
jwt.expiration-seconds=3600

stylefit.vision.yunet-model=classpath:models/face_detection_yunet_2023mar.onnx
stylefit.vision.min-brightness=60
stylefit.vision.max-brightness=210
stylefit.vision.face-score-threshold=0.9
